// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxoTRUM1bYEJasZpptonbKWLnxXVOp2yw',
    appId: '1:909206691880:web:dc90bf1b1a004d0eebd51d',
    messagingSenderId: '909206691880',
    projectId: 'girisim-appx',
    authDomain: 'girisim-appx.firebaseapp.com',
    storageBucket: 'girisim-appx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysY0iiYoP7LkIAoSK0iSB0aZhl6opkIs',
    appId: '1:909206691880:android:649461237c9c44baebd51d',
    messagingSenderId: '909206691880',
    projectId: 'girisim-appx',
    storageBucket: 'girisim-appx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqJX7xcDW7B9QsNNsRNQ1Ie310_U4blU',
    appId: '1:909206691880:ios:4b73174815519acfebd51d',
    messagingSenderId: '909206691880',
    projectId: 'girisim-appx',
    storageBucket: 'girisim-appx.firebasestorage.app',
    iosBundleId: 'com.polimat.girisim.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxoTRUM1bYEJasZpptonbKWLnxXVOp2yw',
    appId: '1:909206691880:web:a1752a7c7a6e251aebd51d',
    messagingSenderId: '909206691880',
    projectId: 'girisim-appx',
    authDomain: 'girisim-appx.firebaseapp.com',
    storageBucket: 'girisim-appx.firebasestorage.app',
  );
}
